# Generated by Django 5.0.4 on 2024-05-18 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_reg', '0003_alter_tournamentevent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='registration_order_non_negative', violation_error_message='The order must be non-negative.'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('tournament_event', 'order'), name='unique_registration_order', violation_error_message='This order already exists.'),
        ),
    ]
